### ISSUE TITLE
作者:工程中的greendaogenerator是什么用的

### ISSUE THREAD

**Issue by x4x5c5** [andforce/Maps#3]
![image](https://cloud.githubusercontent.com/assets/18498743/17318755/79311440-58bb-11e6-87ce-d3d050f33cbb.png)
能不能删了,因为不知道为什么报错了

**Comment by andforce** [comment]
DAO相关的~理论上是可以删除的~要修改数据库就不能动~

**Comment by x4x5c5** [comment]
![screenshot_2016-08-07-10-55-44](https://cloud.githubusercontent.com/assets/18498743/17460197/cf4e696a-5c8d-11e6-8489-7cf8b8369dcd.png)
作者,下面那个开始导航控件在哪个xml设置(那个小按妞)
